// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "web-20190405125850--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1hcg60v05feyj.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:6c082b06-7b0d-44c4-87ef-aed9b79f4a9a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7rTjD4b0u",
    "aws_user_pools_web_client_id": "14npc8gsnnk8u0eml9cjof2or2"
};


export default awsmobile;
